sequenceDiagram
    participant User
    participant FMS
    participant AHS
    participant Equipment

    User->>FMS: Activate All Policy Zones <br/> (Optional) Activation Deadline: ISO 8601 UTC
    FMS->>AHS: Activate All Policy Zones <br/> (Optional) Activation Deadline: ISO 8601 UTC
    AHS->>Equipment: Activate All Policy Zones <br/> (Optional) Activation Deadline: ISO 8601 UTC
    Equipment->>AHS: Accept
    AHS-->>FMS: Accept 202
    FMS-->>User: Pending

    Equipment->>AHS: Activate (Zone 1)
    AHS-->>FMS: ActivateZoneResponseV1 (Zone 1)
    FMS-->>User: Policy Zone 1 Active

    Equipment->>AHS: Activate (Zone 2)
    AHS-->>FMS: ActivateZoneResponseV1 (Zone 2)
    FMS-->>User: Policy Zone 2 Active

