sequenceDiagram
    participant User
    participant FMS
    participant AHS
    participant Equipment

    User->>FMS: Activate Policy Zone <br/> (Optional) Activation Deadline: ISO 8601 UTC
    FMS->>AHS: Activate Policy Zone <br/> (Optional) Activation Deadline: ISO 8601 UTC
    AHS->>Equipment: ActivatePolicyZone <br/> (Optional) Activation Deadline: ISO 8601 UTC
    Equipment->>AHS: Accepted
    AHS-->>FMS: Accept 202
    FMS-->>User: Pending

    Note left of FMS: Zone accepted for all equipment (waiting)

    Equipment->>AHS: Activated
    AHS-->>FMS: ActivateZoneResponseV1
    FMS-->>User: Policy Active

    Note left of FMS: Zone activated for all equipment (waiting)